### ISSUE TITLE
Theme Lavender 

### ISSUE THREAD

**Issue by Master-Antonio** [NicolasSiver/nodebb-plugin-ns-points#1]
/account/profile.tpl  there isn't in Theme Lavender.
What file have i to edit?

**Comment by NicolasSiver** [comment]
Theme Lavender is super set for theme Vanilla. So you could update profile template in Vanilla - node_modules/nodebb-theme-vanilla

**Comment by Master-Antonio** [comment]
Same Code?

<div class="text-center account-stats">

    <div class="inline-block text-center">
        <span class="human-readable-number" title="{reputation}">{reputation}</span>
        <span class="account-bio-label">[[global:reputation]]</span>
    </div>

    <div class="inline-block text-center">
        <span class="human-readable-number" title="{postcount}">{postcount}</span>
        <span class="account-bio-label">[[global:posts]]</span>
    </div>

    <div class="inline-block text-center">
        <span class="human-readable-number" title="{profileviews}">{profileviews}</span>
        <span class="account-bio-label">[[user:profile_views]]</span>
    </div>

    
    <div class="inline-block text-center">
        <span class="human-readable-number" title="{points}">{points}</span>
        <span class="account-bio-label">Points</span>
    </div>
    

</div>

**Comment by NicolasSiver** [comment]
yes, `{points}` should be available ;)
