### ISSUE TITLE
Just installed it on node bb 1.9.0 but the /points is empty

### ISSUE THREAD

**Issue by FaizanZahid** [NicolasSiver/nodebb-plugin-ns-points#10]
When i visit /points, it shows an empty page. I am using persona theme. is this compatible? fully?

**Comment by eshohet** [comment]
Same problem here, currently looking into it.

**Comment by NicolasSiver** [comment]
Hello. 

Did you start to use the plugin? The plugin should be activated and some action should happen (to have points). If you have an opportunity to test with a previous version `1.8.x`. It would be helpful.

**Comment by FaizanZahid** [comment]
When i activated the plugin on 1.9.2, our shoutbox images get super big :D like this

![image](https://user-images.githubusercontent.com/9073066/40302672-ca6bc968-5ce7-11e8-8101-22909b10928a.png)

When you said some action, what do you mean exactly, what do we need to know or do in order to start the plugin after activation?

Also, do you know which plugin is better and has more features, this or https://www.npmjs.com/package/nodebb-plugin-gamification

PS: @NicolasSiver  i love your social plugins, you do stuff which actually make our users addicted, deep respect for your work 👍 

I can also see the plugin requires some major updates like the ns-awards one:

![image](https://user-images.githubusercontent.com/9073066/40302799-3face2a2-5ce8-11e8-9c7e-65b18b326e20.png)


We see 2 errors in console when we hit /points

![image](https://user-images.githubusercontent.com/9073066/40302911-a6002334-5ce8-11e8-8817-fecd6203e904.png)


@eshohet  what errors do you see on your console?

**Comment by NicolasSiver** [comment]
Plugin Gamification looks like a fork of this plugin. I can recognize some parts and structures.
You have web-socket errors. Maybe there is a crash.

This plugin easily can be broken, since, with every minor version, there are breaking changes in NodeBB.

You are getting points for actions (created topic, likes, created a post).

I will look into it.

**Comment by NicolasSiver** [comment]
The plugin does not work with `1.9`. There is a conflict with a template engine. The nodebb team is actively migrating to Benchpress. Next plugin (v5) will be compatible with NodeBB 1.9

**Comment by FaizanZahid** [comment]
Yes we will be super happy if it starts working with 1.9.x node bb...

Looks like node bb moved to benchpress long ago https://community.nodebb.org/topic/11940/how-to-start-working-with-benchpress/10

Anyway I will wait for ns-points plugin 5, once it's done please update this issue so we can test again ... Thanks
