### ISSUE TITLE
Plugin crashes nodebb server

### ISSUE THREAD

**Issue by UI-Jakob** [NicolasSiver/nodebb-plugin-ns-points#3]
Hi,

Tried this plugin but as soon as I open a post the server crashes.

**Comment by NicolasSiver** [comment]
What do you have in console?

**Comment by UI-Jakob** [comment]
I am very new to nodebb where do I find the console?

**Comment by NicolasSiver** [comment]
You can find logs in console on your server.
When you start nodebb, like this - `./nodebb dev`, it will output errors to console.

**Comment by UI-Jakob** [comment]
My logs are empty.

**Comment by NicolasSiver** [comment]
It should have error, if it crashes server as you said.

**Comment by NicolasSiver** [comment]
Another major version has been released.
